blog/urls.py
from django.urls import path
from . import views
from .views import ProjectPageView, ProjectInfoView
app_name = 'blog'

urlpatterns = [
    path('', views.home_page,
         name='home-page'),
    path('videos/', views.videos_page, name='videos-page'),
    # path('projects/', views.projects_page, name='projects-page'),
    path('projects/', ProjectPageView.as_view(), name='projects-page'),
    # path('projects/details/', views.project_details_page, name='project-info'),
    path('projects/details/<int:pk>', ProjectInfoView.as_view(), name='project-info'),
    path('about-me/', views.about_me_page, name='about-me')
]

website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.contrib.auth.models import User


class Post(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='User', related_name='user_post_fk')
    title = models.CharField(max_length=50, verbose_name='Tile')
    content = models.TextField(verbose_name='Description', null=True, blank=True)
    tech_used = models.CharField(verbose_name='Technology used', max_length=40, null=True, blank=True)
    image = models.ImageField(upload_to='images')
    date_posted = models.DateTimeField(auto_now_add=True)
    repo = models.CharField(max_length=85, verbose_name='Repository', null=True, blank=True)

    def __str__(self):
        return f'{self.user.first_name} - {self.title.title()}'

    class Meta:
        verbose_name = 'Posts'
        verbose_name_plural = 'Posts'


class Album(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='post_albums_fk')
    photos = models.ImageField(upload_to='images/albums')
    date_posted = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.post.title} - Album'

    class Meta:
        verbose_name = 'Albums'
        verbose_name_plural = 'Albums'


class Videos(models.Model):
    title = models.CharField(max_length=30)
    content = models.TextField(null=True, blank=True)
    url = models.CharField(max_length=50)
    date_posted = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.title} - video'

    class Meta:
        verbose_name = 'Video'
        verbose_name_plural = 'Videos'

blog/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Post
from django.views.generic import ListView, DetailView


def home_page(request):
    projects = Post.objects.order_by('-date_posted')[:4]
    return render(request, 'blog/pages/home_page.html', {'projects': projects})


class ProjectPageView(ListView):
    model = Post
    template_name = 'blog/pages/projects_page.html'
    context_object_name = 'projects'
    ordering = ['-date_posted']


# def project_details_page(request):
#     return render(request, 'blog/pages/project_details.html')


class ProjectInfoView(DetailView):
    model = Post
    template_name = 'blog/pages/project_details.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        get_id = self.kwargs['pk']
        get_post = Post.objects.get(pk=get_id)
        try:
            get_albums = get_post.post_albums_fk.all()
        except:
            context['albums'] = ''
        else:
            context['albums'] = get_albums
        return context


def videos_page(request):
    return render(request, 'blog/pages/videos_page.html')


def about_me_page(request):
    return render(request, 'blog/pages/about_me_page.html')

blog/templates/blog/layouts/footer.html
<!-- FOOTER -->
<footer class="container">
    <p class="float-right"><a href="#">Back to top</a></p>
    <p>&copy; 2023-2024 Neil Brian Temblor. &middot; <a href="#">Privacy</a> &middot; <a href="#">Terms</a></p>
</footer>

blog/templates/blog/layouts/header.html
<header>
  <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <a class="navbar-brand" href="{% url 'blog:home-page' %}" style="text-weight: bold;">
      <span class="text-secondary">NB</span><span class="text-warning">PYTHON</span>.DEV
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active mr-2">
          <a class="nav-link" href="{% url 'blog:home-page' %}">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item active mr-2">
          <a class="nav-link" href="{% url 'blog:projects-page' %}">Projects</a>
        </li>
        <li class="nav-item active mr-2">
          <a class="nav-link" href="{% url 'blog:videos-page' %}">Videos</a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'blog:about-me' %}">About me</a>
        </li>
      </ul>
<!--      <form class="form-inline mt-2 mt-md-0">-->
<!--        <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">-->
<!--        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>-->
<!--      </form>-->
    </div>
  </nav>
</header>

blog/templates/blog/layouts/main.html
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="{% static 'blog/images/programmer.png' %}">

    <title>Neil Brian | Portfolio</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'blog/css/main.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'blog/css/carousel.css' %}" rel="stylesheet">
    <link href="{% static 'blog/css/custom-css.css' %}" rel="stylesheet">
  </head>
  <body>
    {% include 'blog/layouts/header.html' %}
    <main role="main">
      {% block content %}
      {% endblock %}
    </main>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="{% static 'blog/js/jquery-slim.min.js' %}"><\/script>')</script>
    <script src="{% static 'blog/js/popper.min.js' %}"></script>
    <script src="{% static 'blog/js/bootstrap.min.js' %}"></script>
    <!-- Just to make our placeholder images work. Don't actually copy the next line! -->
    <script src="{% static 'blog/js/holder.min.js' %}"></script>
    <!--Bootstrap 5-->
<!--    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>-->
  </body>
</html>

blog/templates/blog/pages/about_me_page.html
{% include 'blog/layouts/main.html' %}
{% load static %}

{% block content %}
<div class="container marketing" id="by-section">
    <h2 class="featurette-heading text-center mb-3 fs-5">About Me</span></h2>
    <hr class="featurette-divider">
    <div id="about-me-section">
        <div class="row">
            <div class="col-lg-6">
                <img class="featurette-image img-fluid rounded border border-5" src="{% static 'blog/images/mypic.jpg' %}" height="500" width="500" alt="My Picture">
            </div>
            <div class="col-lg-6">
                <p class="h1 text-primary text-center">
                    Software <span class="text-warning">Developer</span>
                </p>
                <p class="lead mb-2">
                    Welcome to my website! I extend my heartfelt gratitude to each and every one of you for taking the time to visit.
                    I'm Neil Brian Temblor, a dedicated software developer, and I'm thrilled to present to you a collection of my projects
                    and works. Every element you see on this website is a testament to my passion for creating innovative solutions and
                    my commitment to excellence in the world of software development. Thank you for being here, and I
                    hope you enjoy exploring my portfolio.
                </p>
                <p class="lead" style="font-weight: bold;">Social Media Accounts</p>
                <p class="lead">Facebook: <a href="#" class="stretched-link">https://www.facebook.com/Briancore22/</a></p>
                <p class="lead">Instagram: <a href="#" class="stretched-link">https://www.instagram.com/briantemblor22/</a></p>
                <p class="lead">Gmail: <a class="stretched-link text-primary">neilcore22@gmail.com</a></p>
                <p class="lead">Github: <a href="#" class="stretched-link">https://github.com/neilcore</a></p>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12">
                <div class="d-grid gap-2 d-md-flex justify-content-md-end">
                  <a class="btn btn-danger btn-sm text-light me-md-2" role="button">My Resume</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/pages/components/home_page_carousel.html
{% load static %}
<!--Carousel-->
<div id="myCarousel" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="1"></li>
    <li data-target="#myCarousel" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img class="first-slide" src="{% static 'blog/images/carousel.jpg' %}" alt="First slide" height="580">
<!--      <img class="first-slide" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="First slide">-->
      <div class="container">
        <div class="carousel-caption text-left">
          <h1>Learn <span class="text-warning">More</span> About Me.</h1>
          <p>
            I build Software Apps, read anything related to TECH and also about HISTORY as a hobby.
          </p>
          <p><a class="btn btn-lg btn-warning text-dark" href="{% url 'blog:about-me' %}" role="button">More About Me</a></p>
        </div>
      </div>
    </div>
    <div class="carousel-item">
      <img class="second-slide" src="{% static 'blog/images/carousel.jpg' %}" alt="First slide" style="height: 580px;" alt="Second slide">
      <div class="container">
        <div class="carousel-caption">
          <h1>Where Software Meets <span class="text-warning">Success</span></h1>
          <p>
            I have a deep passion for computer software and technologies, as they have the remarkable ability to shape the way our world operates and simplify our
            lives. It's truly fascinating how software can unlock endless possibilities,
            enabling us to create innovative solutions and embark on exciting journeys filled with endless opportunities.  From enhancing efficiency to revolutionizing
            industries, there's no limit to the captivating things that can be accomplished with the power of software.
          </p>
<!--          <p><a class="btn btn-lg btn-warning" href="#" role="button">Learn more</a></p>-->
        </div>
      </div>
    </div>
    <div class="carousel-item">
      <img class="third-slide" src="{% static 'blog/images/carousel.jpg' %}" alt="First slide" style="height: 580px;" alt="Third slide">
      <div class="container">
        <div class="carousel-caption text-right">
          <h1>View my <span class="text-warning">works</span></h1>
          <p>Learning to code has been an incredibly enjoyable journey for me, igniting a spark that turned into a full-blown passion.</p>
          <p><a class="btn btn-lg btn-warning" href="{% url 'blog:projects-page' %}" role="button">Browse projects</a></p>
        </div>
      </div>
    </div>
  </div>
  <a class="carousel-control-prev" href="#myCarousel" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#myCarousel" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
<!--Carousel-->

blog/templates/blog/pages/components/home_page_skills.html
{% load static %}
<hr class="featurette-divider">
<h2 class="featurette-heading text-center mb-5 fw-bold">
    My Skills
</h2>
<div class="row featurette">
  <div class="col-md-7">
    <h2 class="featurette-heading">Programming <span class="text-muted">Languages</span></h2>
    <p class="lead">
        As a software developer, my primary focus and expertise lie in <span class="text-warning" style="font-weight: bold;">Python</span>
        programming language. However, I also possess substantial knowledge and experience in JavaScript, TypeScript, HTML, CSS, and PHP,
        enabling me to effectively work across different programming languages.
    </p>
  </div>
  <div class="col-md-5">
      <img class="featurette-image img-fluid mx-auto" src="{% static 'blog/images/proglang.jpg' %}" height="500" width="500" alt="Generic placeholder image">
<!--            <img class="featurette-image img-fluid mx-auto" data-src="holder.js/500x500/auto" alt="Generic placeholder image">-->
  </div>
</div>

<hr class="featurette-divider">

<div class="row featurette">
  <div class="col-md-7 order-md-2">
    <h2 class="featurette-heading">Object Oriented <span class="text-muted">Programming.</span></h2>
    <p class="lead">
      I have hands-on experience in Object-Oriented Programming (OOP) for a couple of years now, allowing me to effectively
      utilize the principles and concepts of OOP in my software development endeavors.
    </p>
  </div>
  <div class="col-md-5 order-md-1">
    <img class="featurette-image img-fluid mx-auto" src="{% static 'blog/images/OOP.jpg' %}" height="500" width="500" alt="Generic placeholder image">
  </div>
</div>

<hr class="featurette-divider">

<div class="row featurette">
  <div class="col-md-7">
    <h2 class="featurette-heading">Frameworks</h2>
    <p class="lead">
      I have worked extensively with various frameworks, including Django, Django Rest Framework, FastAPI, Laravel, Bootstrap, and ReactJS.
      These frameworks have enabled me to build robust
      and efficient applications by leveraging their powerful features and capabilities.
    </p>
  </div>
  <div class="col-md-5">
    <img class="featurette-image img-fluid mx-auto" src="{% static 'blog/images/frameworks.jpg' %}" height="500" width="500" alt="Generic placeholder image">
  </div>
</div>

<hr class="featurette-divider">

<div class="row featurette">
  <div class="col-md-7 order-md-2">
    <h2 class="featurette-heading">Databases</span></h2>
    <p class="lead">
      As a software developer, I have gained extensive experience working with various databases such as PostgreSQL, MySQL, and Firebase.
    </p>
  </div>
  <div class="col-md-5 order-md-1">
      <img class="featurette-image img-fluid mx-auto" src="{% static 'blog/images/db.jpg' %}" height="500" width="500" alt="Generic placeholder image">
  </div>
</div>

<hr class="featurette-divider">

blog/templates/blog/pages/contact_page.html
{% include 'blog/layouts/main.html' %}
{% load static %}

{% block content %}
{% endblock %}

blog/templates/blog/pages/home_page.html
{% include 'blog/layouts/main.html' %}
{% load static %}

{% block content %}
    {% include 'blog/pages/components/home_page_carousel.html' %}
    <div class="container marketing">
      <div class="d-flex flex-row-reverse">
        <div class="p-2">
            <a href="{% url 'blog:projects-page' %}" class="stretched-link">View more</a>
        </div>
      </div>
      <div class="row mb-2">
        {% for project in projects %}
          <div class="col-md-6">
            <div class="card flex-md-row mb-4 box-shadow h-md-250">
              <div class="card-body d-flex flex-column align-items-start">
                <strong class="d-inline-block mb-2 text-success">Tech</strong>
                <h3 class="mb-0">
                  <a class="text-dark" href="{% url 'blog:project-info' project.id %}">{{ project.title }}</a>
                </h3>
                <div class="mb-1 text-muted">{{ project.date_posted|date:"M d" }}</div>
                <p class="card-text mb-auto">{{ project.content }}</p>
                <a href="{% url 'blog:project-info' project.id %}">View Project</a>
              </div>
              <img class="card-img-right flex-auto d-none d-md-block" src="{{ project.image.url }}" alt="Card image cap" width="200" height="250">
            </div>
          </div>
        {% endfor %}
      </div>

      {% include 'blog/pages/components/home_page_skills.html' %}
    </div>
    {% include 'blog/layouts/footer.html' %}
{% endblock %}

blog/templates/blog/pages/project_details.html
{% include 'blog/layouts/main.html' %}
{% load static %}

{% block content %}
<div class="container marketing" id="by-section">
    <h2 class="featurette-heading text-center mb-5">{{ object.title }}</span></h2>
    <div id="project-detail-section">
        <img src="{{ object.image.url }}" class="img-fluid rounded-1 mb-2 mx-auto d-block border border-5 border-dark rounded" alt="...">
        <p class="lead">
            By: {{ object.user.first_name }} {{ object.user.last_name }}
        </p>
        <p class="lead">
            Tech: {{ object.tech_used }}
        </p>
        <p class="lead">
            Date Posted: {{ object.date_posted|date:"M d, Y" }}
        </p>
        <p class="lead">
            Repository: <a href="#" class="stretched-link">{{ object.repo }}</a>
        </p>
        <p class="lead">
            {{ object.content }}
        </p>

        <p>More Images</p>
        <div id="project-albums">
            {% if albums %}
                {% for album in albums %}
                    <img src="{{ album.photos.url }}" class="img-thumbnail" alt="..." height="200" width="200">
                {% endfor %}
            {% else %}
                <p class="lead">No Albums</p>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/pages/projects_page.html
{% include 'blog/layouts/main.html' %}
{% load static %}

{% block content %}
<div class="container marketing" id="by-section">
    <h2 class="featurette-heading text-center mb-3">Projects</span></h2>
    <hr class="featurette-divider">
    <div id="project-section">
        {% for project in projects %}
            <div class="d-flex justify-content-between">
                <p>{{ project.title }} | {{ project.tech_used }}</p>
                <p>{{ project.date_posted }}</p>
            </div>
            <img src="{{ project.image.url }}" class="img-fluid rounded-1 mb-2 mx-auto d-block">
            <div class="d-grid gap-2 d-md-flex justify-content-md-end mb-5">
              <a class="btn btn-secondary me-md-2 mr-2 btn-sm text-light" role="button" disabled href="{% url 'blog:project-info' project.id %}">
                  View
              </a>
              <a class="btn btn-dark btn-sm text-light" role="button" disable title="Unavailable" href="{{ project.repo|default:'#' }}">
                  Github
              </a>
            </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

blog/templates/blog/pages/videos_page.html
{% include 'blog/layouts/main.html' %}
{% load static %}

{% block content %}
<div class="container marketing" id="by-section">
    <h2 class="featurette-heading text-center">Videos</span></h2>
    <hr class="featurette-divider">
</div>
{% endblock %}